name: Android Setup
description: Set up for Android build
inputs:
  gpg-pass-phrase:
    description: 'GPG passphrase for secrets'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/basic-setup
    - name: Set Env
      run: echo ${{ inputs.gpg-pass-phrase }}
      shell: bash
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'
    - name: Gradle cache
      uses: gradle/gradle-build-action@v2
      shell: bash
    - name: Install Fastlane
      run: cd ios && bundle install && cd ..
      shell: bash
    - name: Make secrets
      run: GPG_PASSPHRASE=${{ inputs.gpg-pass-phrase }} make secrets
      shell: bash
