# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    get_certificates(
      api_key: api_key
    )           # invokes cert
    get_provisioning_profile(
      api_key: api_key
    )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
  end
end
