# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    get_certificates(
      api_key: api_key
    )           # invokes cert
    get_provisioning_profile(
      api_key: api_key
    )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
  end

  lane :github_beta do
    create_keychain(
      name: "ios_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    import_certificate(
      certificate_path: 'H9Y76D7587.p12',
      certificate_password: ENV["FASTLANE_PASSWORD"],
      keychain_name: 'ios_keychain',
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )
    install_provisioning_profile(path: 'comEnumeDate_AppStore.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'EnumeDate.xcodeproj',
      profile: 'comEnumeDate_AppStore.mobileprovision',
      build_configuration: 'Release'
    )
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    # get_certificates(
    #   api_key: api_key
    # )           # invokes cert
    # get_provisioning_profile(
    #   api_key: api_key
    # )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", export_method: "app-store", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
    delete_keychain
  end

  lane :github_beta_new do
    create_keychain(
      name: "ios_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    import_certificate(
      certificate_path: 'distribution.p12',
      certificate_password: ENV["FASTLANE_PASSWORD"],
      keychain_name: 'ios_keychain',
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )
    install_provisioning_profile(path: 'comEnumeDate_AppStore.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'EnumeDate.xcodeproj',
      profile: 'comEnumeDate_AppStore.mobileprovision',
      build_configuration: 'Release'
    )
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    # get_certificates(
    #   api_key: api_key
    # )           # invokes cert
    # get_provisioning_profile(
    #   api_key: api_key
    # )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", export_method: "app-store", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
    delete_keychain
  end

  lane :github_beta_new_test do
    create_keychain(
      name: "ios_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    import_certificate(
      certificate_path: 'distribution-new.p12',
      certificate_password: ENV["FASTLANE_PASSWORD"],
      keychain_name: 'ios_keychain',
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )
    install_provisioning_profile(path: 'comEnumeDate_AppStore.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'EnumeDate.xcodeproj',
      profile: 'comEnumeDate_AppStore.mobileprovision',
      build_configuration: 'Release'
    )
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    # get_certificates(
    #   api_key: api_key
    # )           # invokes cert
    # get_provisioning_profile(
    #   api_key: api_key
    # )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", export_method: "app-store", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
    delete_keychain
  end

  lane :github_beta_new_with_setup do
    setup_ci(force: true)
    create_keychain(
      name: "ios_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    import_certificate(
      certificate_path: 'distribution.p12',
      certificate_password: ENV["FASTLANE_PASSWORD"],
      keychain_name: 'ios_keychain',
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )
    install_provisioning_profile(path: 'comEnumeDate_AppStore.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'EnumeDate.xcodeproj',
      profile: 'comEnumeDate_AppStore.mobileprovision',
      build_configuration: 'Release'
    )
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    # get_certificates(
    #   api_key: api_key
    # )           # invokes cert
    # get_provisioning_profile(
    #   api_key: api_key
    # )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", export_method: "app-store", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
    delete_keychain
  end

  lane :github_beta_new_test_with_setup do
    setup_ci(force: true)
    create_keychain(
      name: "ios_keychain",
      password: ENV["FASTLANE_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    import_certificate(
      certificate_path: 'distribution-new.p12',
      certificate_password: ENV["FASTLANE_PASSWORD"],
      keychain_name: 'ios_keychain',
      keychain_password: ENV["FASTLANE_PASSWORD"]
    )
    install_provisioning_profile(path: 'comEnumeDate_AppStore.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'EnumeDate.xcodeproj',
      profile: 'comEnumeDate_AppStore.mobileprovision',
      build_configuration: 'Release'
    )
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    # get_certificates(
    #   api_key: api_key
    # )           # invokes cert
    # get_provisioning_profile(
    #   api_key: api_key
    # )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", export_method: "app-store", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
    delete_keychain
  end

  lane :github_beta_basic do
    increment_build_number(xcodeproj: "EnumeDate.xcodeproj")
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: 'distribution.p8'
    )
    get_certificates(
      api_key: api_key
    )           # invokes cert
    get_provisioning_profile(
      api_key: api_key
    )   # invokes sigh
    build_app(workspace: "EnumeDate.xcworkspace", scheme: "EnumeDate", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key: api_key
    )
  end

  
end
