name: Test setup
description: Basic setup for tests

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      run: yarn install
      shell: bash
    - name: Build Tailwind
      run: yarn build:tailwind
      shell: bash
