name: iOS Setup
description: Set up for iOS build

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/basic-setup
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'
    - uses: actions/cache@v2
      with:
        path: '**/Pods'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/Podfile.lock') }}-dependency-${{ hashFiles('**/yarn.lock') }}
    - name: Install Pods
      run: cd ios && pod install && cd ..
      shell: bash
    - name: Install Fastlane
      run: cd ios && bundle install && cd ..
      shell: bash
