# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean assembleReleaseE2E assembleAndroidTest -DtestBuildType=releaseE2E")
  end

  desc "Build a debug"
  lane :debug_build do
    gradle(task: "clean assembleDebug")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build a release aab"
  lane :release_aab do
    gradle(task: "clean bundleRelease")
    # upload_to_play_store
  end
end
