# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Bump version code"
  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean assembleReleaseE2E assembleAndroidTest -DtestBuildType=releaseE2E")
  end

  desc "Build a debug"
  lane :debug_build do
    gradle(task: "clean assembleDebug")
  end

  desc "Build a release aab"
  lane :release_aab_alpha do
    bump_version_code
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'alpha', release_status: "draft")
  end
end
