name: Android Debug

on:
  push:
    branches:
      - '*'
jobs:
  android-debug:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Build tailwind
        run: yarn build:tailwind
      - name: Prebuild
        run: mkdir android/app/src/main/assets && make build_android_debug
      - name: Execute Fastlane command
        run: cd android && fastlane debug_build
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
