name: Android Debug

on:
  push:
    branches:
      - 'master'
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  call-integration-test-workflow:
    uses: ./.github/workflows/tests.yaml
  android-debug:
    name: Build Android Debug
    needs: call-integration-test-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/android-setup
        name: Setup Android
        with:
          gpg-pass-phrase: ${GPG_PASSPHRASE}
      - name: Prebuild
        run: mkdir android/app/src/main/assets && make build_android_debug
      - name: Execute Fastlane command
        run: cd android && fastlane debug_build
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
