name: Android E2E Tests

on:
  push:
    branches:
      - '*'
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  android-tests:
    name: Build Android Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Download Android Emulator Image
        run: sh ./android/fastlane/download-android-emulator-image.sh
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Build tailwind
        run: yarn build:tailwind
      - name: Make secrets
        run: GPG_PASSPHRASE=${GPG_PASSPHRASE} make secrets
      - name: Setup detox
        run: brew tap wix/brew
      - name: Build Test Version
        run: yarn detox build --configuration android
      - name: Android Emulator
        timeout-minutes: 10
        continue-on-error: true
        run: sh ./android/fastlane/start-emulator.sh
      - name: Test Buid
        run: yarn detox test --configuration android
