name: iOS Tetss

on:
  push:
    branches:
      - '*'

jobs:
  github-beta:
    name: Build and Deploy Beta
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
      DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
      APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
      APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
      APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
      GIT_URL: '${{secrets.GIT_URL}}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.x'
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - uses: actions/cache@v2
        with:
          path: '**/Pods'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Podfile.lock') }}-dependency-${{ hashFiles('**/yarn.lock') }}
      - name: Install Pods
        run: cd ios && pod install && cd ..
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Build tailwind
        run: yarn build:tailwind
      - name: Setup detox
        run: brew tap wix/brew && brew install applesimutils
      - name: Build Test Version
        run: yarn detox build --configuration ios
      - name: Test Build
        run: yarn detox test --configuration ios
