name: iOS Beta

on:
  push:
    branches:
      - '*'
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  FASTLANE_IOS_SECRET: ${{ secrets.FASTLANE_IOS_SECRET}}

jobs:
  ios-beta:
    name: Build and Deploy Beta
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Make secrets
        run: GPG_PASSPHRASE=${GPG_PASSPHRASE} make secrets
      - name: Execute Fastlane command
        run: cd ios && FASTLANE_PASSWORD=${FASTLANE_IOS_SECRET} fastlane beta
      - name: Install packages
        run: yarn install
      - name: Build tailwind
        run: yarn build:tailwind
      - name: Install pods
        run: cd ios && pod install && cd ..
