# name: Caching with iOS
# on: push
# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Cache pods
#         id: cache-ios
#         uses: actions/cache@v3
#         env:
#           cache-name: cache-pods
#         with:
#           path: ~/ios/Pods
#           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Podfile.lock') }}-${{ hashFiles('**/Podfile') }}
#           restore-keys: |
#             ${{ runner.os }}-build-${{ env.cache-name }}-
#             ${{ runner.os }}-build-
#             ${{ runner.os }}-

#       - if: ${{ steps.cache-ios.outputs.cache-hit == 'false' }}
#         name: List the state of node modules
#         continue-on-error: true
#         run: cd ios && pod list

#       - name: Install dependencies
#         run: cd ios && pod install
