name: Integration Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  tests:
    name: Run Integration Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/basic-setup
        name: Basic setup
      - name: Tests
        run: yarn test
